//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeziRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int Id { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<byte> IsActive { get; set; }
    
        public virtual Blogs Blogs1 { get; set; }
        public virtual Blogs Blogs2 { get; set; }
        public virtual Blogs Blogs11 { get; set; }
        public virtual Blogs Blogs3 { get; set; }
    }
}
