//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeziRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Places Places1 { get; set; }
        public virtual Places Places2 { get; set; }
        public virtual Places Places11 { get; set; }
        public virtual Places Places3 { get; set; }
    }
}
