//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeziRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int Id { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Ratings Ratings1 { get; set; }
        public virtual Ratings Ratings2 { get; set; }
        public virtual Ratings Ratings11 { get; set; }
        public virtual Ratings Ratings3 { get; set; }
    }
}
